CREATE TABLE "trader_actions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_actions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"action_type" text NOT NULL,
	"symbol" text,
	"exchange" text,
	"qty" integer,
	"side" text,
	"order_id" text,
	"error" text,
	"pnl_rs" double precision,
	"pnl_pct" double precision,
	"day_pnl" double precision,
	"rule_id" integer
);
--> statement-breakpoint
CREATE TABLE "trader_config" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trader_daily_summary" (
	"date" date PRIMARY KEY NOT NULL,
	"n_trades" integer DEFAULT 0 NOT NULL,
	"n_wins" integer DEFAULT 0 NOT NULL,
	"n_losses" integer DEFAULT 0 NOT NULL,
	"gross_pnl" double precision DEFAULT 0 NOT NULL,
	"total_charges" double precision DEFAULT 0 NOT NULL,
	"net_pnl" double precision DEFAULT 0 NOT NULL,
	"win_rate" double precision,
	"avg_win" double precision,
	"avg_loss" double precision,
	"largest_win" double precision,
	"largest_loss" double precision,
	"notes" text,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "kite_instruments" (
	"instrument_token" bigint PRIMARY KEY NOT NULL,
	"exchange_token" bigint NOT NULL,
	"tradingsymbol" text NOT NULL,
	"name" text,
	"last_price" double precision,
	"expiry" date,
	"strike" double precision,
	"tick_size" double precision,
	"lot_size" integer,
	"instrument_type" text,
	"segment" text,
	"exchange" text NOT NULL,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trader_knowledge_entries" (
	"date" date PRIMARY KEY NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trader_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"started_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "trader_polls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_polls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"total_pnl" double precision NOT NULL,
	"n_positions" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trader_position_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_position_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"poll_id" integer NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"symbol" text NOT NULL,
	"exchange" text NOT NULL,
	"side" text NOT NULL,
	"qty" integer NOT NULL,
	"avg_price" double precision NOT NULL,
	"ltp" double precision NOT NULL,
	"pnl_rs" double precision NOT NULL,
	"pnl_pct" double precision NOT NULL,
	"flag" text,
	"rule_id" integer
);
--> statement-breakpoint
CREATE TABLE "cms_post_meta" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cms_post_meta_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" integer NOT NULL,
	"meta_key" text NOT NULL,
	"meta_value" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cms_posts" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cms_posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"content" text DEFAULT '' NOT NULL,
	"published" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cms_posts_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "auth_sessions" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trader_tape_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_tape_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ts" timestamp with time zone NOT NULL,
	"symbol" text NOT NULL,
	"ltp" double precision NOT NULL,
	"day_open" double precision,
	"day_high" double precision,
	"day_low" double precision,
	"prev_close" double precision,
	"pct_change" double precision,
	"volume" bigint,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "trader_trades" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_trades_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"symbol" text NOT NULL,
	"exchange" text NOT NULL,
	"side" text NOT NULL,
	"setup_tag" text,
	"buy_ts" timestamp with time zone NOT NULL,
	"buy_price" double precision NOT NULL,
	"buy_qty" integer NOT NULL,
	"buy_value" double precision NOT NULL,
	"buy_order_id" text,
	"sell_ts" timestamp with time zone NOT NULL,
	"sell_price" double precision NOT NULL,
	"sell_qty" integer NOT NULL,
	"sell_value" double precision NOT NULL,
	"sell_order_id" text,
	"gross_pnl" double precision NOT NULL,
	"brokerage" double precision NOT NULL,
	"stt" double precision NOT NULL,
	"txn_charges" double precision NOT NULL,
	"sebi_charges" double precision NOT NULL,
	"stamp_duty" double precision NOT NULL,
	"gst" double precision NOT NULL,
	"total_charges" double precision NOT NULL,
	"net_pnl" double precision NOT NULL,
	"held_min" double precision NOT NULL,
	"sl_initial" double precision,
	"tp_initial" double precision,
	"sl_final" double precision,
	"peak_ltp" double precision,
	"risk_initial" double precision,
	"realized_r" double precision,
	"exit_reason" text,
	"rule_id" integer,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_users" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "auth_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"password_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "auth_users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "trader_watch_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_watch_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"exchange" text DEFAULT 'NSE' NOT NULL,
	"sl_pct" double precision,
	"tp_pct" double precision,
	"sl_price" double precision,
	"tp_price" double precision,
	"status" text DEFAULT 'active' NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"entry_ts" timestamp with time zone,
	"peak_ltp" double precision,
	"be_armed" boolean DEFAULT false NOT NULL,
	"time_stop_min" integer DEFAULT 30 NOT NULL,
	"giveback_pct" double precision DEFAULT 50 NOT NULL,
	"auto_manage" boolean DEFAULT true NOT NULL,
	"sl_mode" text DEFAULT 'ltp' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trader_would_have_taken" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trader_would_have_taken_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"symbol" text NOT NULL,
	"exchange" text DEFAULT 'NSE' NOT NULL,
	"setup" text NOT NULL,
	"side" text NOT NULL,
	"entry" double precision NOT NULL,
	"sl" double precision NOT NULL,
	"tp" double precision NOT NULL,
	"qty" integer NOT NULL,
	"reject_reason" text NOT NULL,
	"reject_detail" text,
	"is_in_universe" boolean DEFAULT true NOT NULL,
	"is_sector_leader" boolean,
	"sector_index" text,
	"sector_chg_pct" double precision,
	"nifty_chg_pct" double precision,
	"vix_value" double precision,
	"sess_high_after" double precision,
	"sess_low_after" double precision,
	"eod_close" double precision,
	"hit_tp" boolean,
	"hit_sl" boolean,
	"hyp_net_pnl" double precision,
	"backfilled_at" timestamp with time zone,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "kite_tokens" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "kite_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kite_user_id" text NOT NULL,
	"user_name" text,
	"user_shortname" text,
	"email" text,
	"broker" text,
	"access_token" text NOT NULL,
	"public_token" text,
	"refresh_token" text,
	"enctoken" text,
	"login_time" timestamp with time zone,
	"expires_at" timestamp with time zone NOT NULL,
	"exchanges" text[],
	"products" text[],
	"order_types" text[],
	"raw_response" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "trader_actions" ADD CONSTRAINT "trader_actions_session_id_trader_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."trader_sessions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trader_actions" ADD CONSTRAINT "trader_actions_rule_id_trader_watch_rules_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."trader_watch_rules"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trader_polls" ADD CONSTRAINT "trader_polls_session_id_trader_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."trader_sessions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trader_position_snapshots" ADD CONSTRAINT "trader_position_snapshots_poll_id_trader_polls_id_fk" FOREIGN KEY ("poll_id") REFERENCES "public"."trader_polls"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trader_position_snapshots" ADD CONSTRAINT "trader_position_snapshots_rule_id_trader_watch_rules_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."trader_watch_rules"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cms_post_meta" ADD CONSTRAINT "cms_post_meta_post_id_cms_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."cms_posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cms_posts" ADD CONSTRAINT "cms_posts_user_id_auth_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."auth_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_sessions" ADD CONSTRAINT "auth_sessions_user_id_auth_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."auth_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trader_trades" ADD CONSTRAINT "trader_trades_rule_id_trader_watch_rules_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."trader_watch_rules"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_trader_actions_ts" ON "trader_actions" USING btree ("ts");--> statement-breakpoint
CREATE INDEX "idx_kite_instruments_tsym" ON "kite_instruments" USING btree ("tradingsymbol");--> statement-breakpoint
CREATE INDEX "idx_kite_instruments_exch" ON "kite_instruments" USING btree ("exchange");--> statement-breakpoint
CREATE INDEX "idx_trader_polls_ts" ON "trader_polls" USING btree ("ts");--> statement-breakpoint
CREATE INDEX "idx_trader_position_snapshots_ts" ON "trader_position_snapshots" USING btree ("ts");--> statement-breakpoint
CREATE INDEX "idx_trader_position_snapshots_sym" ON "trader_position_snapshots" USING btree ("symbol");--> statement-breakpoint
CREATE UNIQUE INDEX "cms_post_meta_post_id_meta_key_unique" ON "cms_post_meta" USING btree ("post_id","meta_key");--> statement-breakpoint
CREATE INDEX "idx_trader_tape_snapshots_ts" ON "trader_tape_snapshots" USING btree ("ts");--> statement-breakpoint
CREATE INDEX "idx_trader_tape_snapshots_sym" ON "trader_tape_snapshots" USING btree ("symbol","ts");--> statement-breakpoint
CREATE INDEX "idx_trader_trades_date" ON "trader_trades" USING btree ("date");--> statement-breakpoint
CREATE INDEX "idx_trader_trades_symbol" ON "trader_trades" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "idx_trader_watch_rules_active" ON "trader_watch_rules" USING btree ("symbol","exchange","status");--> statement-breakpoint
CREATE INDEX "idx_trader_would_have_taken_date" ON "trader_would_have_taken" USING btree ("date");--> statement-breakpoint
CREATE INDEX "idx_trader_would_have_taken_symbol" ON "trader_would_have_taken" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "idx_trader_would_have_taken_setup" ON "trader_would_have_taken" USING btree ("setup");--> statement-breakpoint
CREATE INDEX "idx_trader_would_have_taken_reason" ON "trader_would_have_taken" USING btree ("reject_reason");